### ISSUE TITLE
PSASS command not found

### ISSUE THREAD

**Issue by orijitghosh** [RomainFeron/PSASS#1]
Hi,
I built PSASS using make, but when I am trying to use it, it shows psass: command not found error. Please help.
Thanks in advance.

**Comment by RomainFeron** [comment]
Hi,
Building psass creates the binaries (including psass), but by default these binaries are found in the "bin" folder in the PSASS directory. To run psass, you can either give the full path to the psass binary, so "/path/to/psass/folder/bin/psass" or copy / symlink the psass binary to a folder that is part of your PATH (echo $PATH), like usually /usr/bin. Let me know if this solved your issue.

**Comment by orijitghosh** [comment]
Thank you so much. Yes that solved my problems.

**Comment by orijitghosh** [comment]
Also, in my sync file the populations are arranged as:
C1-E1-C2-E2-C3-E3-C4-E4 where C is control population and E is experimental population, is this arrangement fine?

**Comment by RomainFeron** [comment]
I developed PSASS to look for sex signal, so by design it can only handle two populations.
In your case, if you want to use PSASS, there are two solutions:
- Merge all control and experimental populations
- Compute statistics for all pairs of C/E
If you need a tool to compute global statistics for your replicates, then I think PSASS is not the best.

**Comment by orijitghosh** [comment]
Okay, then I think I will compute statistics for all pairs of C/E separately. Thank you, closing this issue now.
